# Exploratory data analysis

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Import data

In [18]:
df_returns = pd.read_csv('data/returns.csv')
# Convert columns to lowercase
df_returns.columns = [col.lower() for col in df_returns.columns]

df_kcal = pd.read_csv('data/kcal.csv')
df_kcal.columns = [col.lower() for col in df_kcal.columns]

df_recall = pd.read_csv('data/recall.csv')
df_recall.columns = [col.lower() for col in df_recall.columns]

df_group = pd.read_csv('data/groups.csv')
df_group.columns = [col.lower() for col in df_group.columns]

In [53]:
# make dates have some format
df_group['date'] = pd.to_datetime(df_group['date'], dayfirst=True)
df_returns['date'] = pd.to_datetime(df_returns['date'], dayfirst=True)

#df_group['date'] = df_group['date'].dt.strftime('%Y-%m-%d')
df_group.head()

,date,id,group,date_depart,depart,date_arrive,arrive,activity,activity.type,time.out,total.minutes,precision
0,2018-08-02,1006,0,02/08/2018,17.42,02/08/2018,17.58,Palm wine,Foraging,0.16,16,Observed
1,2018-08-10,1006,0,10/08/2018,12.41,10/08/2018,13.48,Slingshot hunting,Foraging,1.07,67,Observed
2,2018-08-10,1006,0,10/08/2018,14.31,10/08/2018,14.45,Palm wine,Foraging,0.14,14,Observed
3,2018-08-17,1006,0,17/08/2018,10.55,17/08/2018,11.29,Slingshot hunting,Foraging,0.34,34,Observed
4,2018-08-14,1008,0,14/08/2018,10.08,14/08/2018,10.30,Garden,Foraging,0.22,22,Observed

In [19]:
df_kcal.head()

   index    yaka      english     processing_condition       kcal.g
0      1    Mobe      Unknown                    whole  0.597857143
1      2  Maondo      Unknown                    whole  0.224772727
2      3   Maika         Taro   Tuber without periderm         1.27
3      4   Dunda  Taro leaves      Leaves with petiole        0.234
4      5   Mbila     Palm nut  many fruits with bracts         2.97

In [35]:
df_returns.head()

,date,pooled_group,index,net_food_weight_gram,gift,id,article,state
0,01.08.18,1.0,55,1100.0,0.0,1030,ediki,with inedible
1,01.08.18,1.0,55,1100.0,0.0,2523,ediki,with inedible
2,01.08.18,1.0,55,1100.0,0.0,1010,ediki,with inedible
3,01.08.18,10.0,14,100.0,0.0,2513,ekule,ready-to-eat
4,01.08.18,10.0,14,100.0,0.0,2039,ekule,ready-to-eat

pandas.core.series.Series

In [21]:
df_recall.head()
df_recall.count()

,date,gift,id,pooled_group,article_consumed,quantity,x1_unit_weight_grams,index,source,total_weight_grams
0,23/07/2018,0,1032,0,maondo-with peel,5.0,429,2.0,fieldnotes.,2145.0
1,23/07/2018,0,1102,0,palm nuts,10.0,9,8.0,"Davies, R. M. (2012). Physical and mechanical ...",90.0
2,24/07/2018,0,3041,0,orange,1.0,131,45.0,USDA with peel.,131.0
3,25/07/2018,0,3077,0,palm nuts,10.0,9,8.0,"Davies, R. M. (2012). Physical and mechanical ...",90.0
4,26/07/2018,0,2513,0,honey,0.5,1420,91.0,"According to U.S. Department of Agriculture, ...",710.0

In [38]:
df_group.head()

,date,id,group,date_depart,depart,date_arrive,arrive,activity,activity.type,time.out,total.minutes,precision
0,02/08/2018,1006,0,02/08/2018,17.42,02/08/2018,17.58,Palm wine,Foraging,0.16,16,Observed
1,10/08/2018,1006,0,10/08/2018,12.41,10/08/2018,13.48,Slingshot hunting,Foraging,1.07,67,Observed
2,10/08/2018,1006,0,10/08/2018,14.31,10/08/2018,14.45,Palm wine,Foraging,0.14,14,Observed
3,17/08/2018,1006,0,17/08/2018,10.55,17/08/2018,11.29,Slingshot hunting,Foraging,0.34,34,Observed
4,14/08/2018,1008,0,14/08/2018,10.08,14/08/2018,10.30,Garden,Foraging,0.22,22,Observed

In [54]:
# Merge to get kcal as rate
df_merged = pd.merge(df_returns, df_kcal[['index', 'kcal.g']], on='index', how='left').merge(df_group[['date','id', 'total.minutes']], on=['id', 'date'], how='left')

In [55]:
df_merged.head()

,date,pooled_group,index,net_food_weight_gram,gift,id,article,state,kcal.g,total.minutes
0,2018-08-01,1.0,55,1100.0,0.0,1030,ediki,with inedible,0.1225,16.0
1,2018-08-01,1.0,55,1100.0,0.0,1030,ediki,with inedible,0.1225,2.0
2,2018-08-01,1.0,55,1100.0,0.0,1030,ediki,with inedible,0.1225,1.0
3,2018-08-01,1.0,55,1100.0,0.0,2523,ediki,with inedible,0.1225,25.0
4,2018-08-01,1.0,55,1100.0,0.0,2523,ediki,with inedible,0.1225,15.0